name: rag-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - langchain==0.1.12
    - chromadb==0.4.24
    - sentence-transformers==2.5.1
    - boto3==1.34.69
    - streamlit==1.32.2
    - python-dotenv==1.0.1 